name: flutter_cleaner
description: A tool to delete obsolete build folders
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^3.1.0
  macos_ui: ^2.2.0
  path: ^1.8.2
  pubspec_parse: ^1.2.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3

dev_dependencies:
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - pubspec.yaml
